general {
    no_fade_in = false
    no_fade_out = false
    grace = 0
}

background {
    monitor =
    path = screenshot
    blur_passes = 5
    blur_size = 1
}

# Password input (clean centered bar)
input-field {
    monitor =
    size = 400, 55
    position = 0, -60

    rounding = 16

    outer_color = rgba(0, 0, 0, 0.0)
    inner_color = rgba(20, 20, 20, 0.55)

    font_color = rgb(255, 255, 255)

    placeholder_text = Enter password
    hide_input = false

    dots_center = true
    fade_on_empty = false

    outline_thickness = 2
    outline_color = rgba(255, 255, 255, 0.15)
}

label {
    monitor =
    text = $TIME
    font_size = 50
    position = 0, 120
    color = rgb(255, 255, 255)
}
